# Generated by Django 4.2.8 on 2023-12-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('autores', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autores de la publicación separados por ;')),
                ('ano_publicacion', models.SmallIntegerField(blank=True, null=True, verbose_name='Año de publicacion')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección en el servidor correspondiente')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cdinf', models.CharField(default='INDESCA', max_length=50, verbose_name='C. de Inf.')),
                ('cdlc', models.CharField(max_length=50, verbose_name='Clasificación de LC')),
                ('cdcuter', models.CharField(max_length=50, verbose_name='Código de Cuter')),
                ('cddewey', models.CharField(max_length=50, verbose_name='Código de Dewey')),
                ('descriptores', models.ManyToManyField(blank=True, to='core.descriptor')),
            ],
            options={
                'ordering': ('titulo', 'ano_publicacion'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('autores', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autores de la publicación separados por ;')),
                ('ano_publicacion', models.SmallIntegerField(blank=True, null=True, verbose_name='Año de publicacion')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección en el servidor correspondiente')),
                ('no_registro', models.CharField(max_length=50, unique=True)),
                ('codigo_proyecto', models.CharField(max_length=50, unique=True)),
                ('descriptores', models.ManyToManyField(blank=True, to='core.descriptor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'ordering': ('titulo', 'ano_publicacion'),
                'abstract': False,
            },
        ),
    ]
