# Generated by Django 4.2.8 on 2023-12-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_libro_cdcuter_alter_libro_cddewey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='codigo_proyecto',
            field=models.CharField(max_length=50),
        ),
    ]
