# Generated by Django 4.2.8 on 2023-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_empresa_nombre_alter_informe_codigo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptor',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
