# Generated by Django 4.2.8 on 2023-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_descriptor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='solicitud_servicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
