# Generated by Django 4.2.8 on 2024-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_informe_solicitud_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='direccion',
        ),
        migrations.AddField(
            model_name='informe',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
