# Generated by Django 4.2.8 on 2024-01-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_informe_direccion_remove_libro_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='media/libros/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='media/libros/', verbose_name='Archivo'),
        ),
    ]
