# Generated by Django 4.2.8 on 2024-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_informe_archivo_alter_libro_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterField(
            model_name='informe',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='libros/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='libros/', verbose_name='Archivo'),
        ),
    ]
