# Generated by Django 4.2.8 on 2024-01-03 11:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_empresa_options_alter_informe_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='archivo',
            field=models.FileField(blank=True, max_length=200, null=True, unique=True, upload_to=core.models.Informe.upload_to, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
