# Generated by Django 4.2.8 on 2024-01-03 11:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_informe_archivo_alter_informe_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='archivo',
            field=models.FileField(max_length=200, null=True, unique=True, upload_to=core.models.Informe.upload_to, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cdcuter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código de Cuter'),
        ),
    ]
