# Generated by Django 4.2.8 on 2024-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_informe_archivo_alter_libro_cdcuter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptor',
            name='nombre',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
