# Generated by Django 4.2.8 on 2024-01-03 11:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_descriptor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='archivo',
            field=models.FileField(max_length=200, null=True, upload_to=core.models.Informe.upload_to, verbose_name='Archivo'),
        ),
    ]
