# Generated by Django 4.2.8 on 2024-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_informe_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='solicitud_servicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
